apiVersion: v1
kind: Service
metadata:
  name: devops-lab-service
spec:
  type: LoadBalancer
  selector:
    app: devops-lab-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000